using System.Collections;
using System.Collections.Generic;
using UnityEngine;


namespace MinVR {

    /* Implementing this interface will make it possible for a class to act like a
     * virtual input device.  After registering the class with VRMain, it will be
     * polled once each frame to collect any new events generated.
     */
    public interface VREventGenerator {
        /// Concrete implementations of VREventGenerator should override this method and
        /// add events generated by the device to the list provided.  This method
        /// is called once per frame to collect all of the input events generated
        /// since the previous frame.
        void AddEventsSinceLastFrame(ref List<VREvent> eventList);
    }
}
